name: Generate Snake (2026)

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily
  workflow_dispatch:       # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake (2026 only)
        uses: Platane/snk@v3
        with:
          github_user_name: Shamsun-Nahar-Nitu
          year: 2026
          outputs: |
            dist/snake.svg

      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
